-- ============================================================================
-- 01-estructura-sin-funciones.sql
-- Sistema de Gestión y Reservas de Equipos del LIS
-- PostgreSQL / Supabase
-- Versión simplificada y estable (sin funciones, triggers ni vistas)
--
-- IMPORTANTE:
--   1. Este archivo ELIMINA únicamente los objetos del proyecto SistemaReservasLIS
--      y los vuelve a crear desde cero.
--   2. No elimina el esquema public ni objetos internos de Supabase.
--   3. Está pensado para ejecutarse con el botón normal "Run".
--   4. RLS se habilita explícitamente al final; NO es necesario usar
--      "Run and enable RLS".
--
-- Qué conserva del modelo:
--   - 20 tablas.
--   - PK y FK.
--   - UNIQUE.
--   - CHECK.
--   - índices.
--   - integridad referencial.
--   - autenticación Google/local.
--   - sesiones/refresh token.
--   - recuperación de contraseña.
--   - inventario.
--   - reservas.
--   - configuración.
--   - auditoría.
--
-- Qué se deja deliberadamente al backend:
--   - Google SSO y validación real del token.
--   - validación del dominio usando tbl_configuracion.
--   - generación/verificación Argon2id.
--   - JWT.
--   - rotación de refresh token.
--   - recuperación de contraseña.
--   - asignación automática de rol base.
--   - disponibilidad derivada DISPONIBLE/RESERVADO.
--   - prevención transaccional de solapamientos.
--   - HTTP 409 Conflict.
--   - auditoría automática de acciones.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 0. LIMPIEZA SEGURA DEL PROYECTO
-- ============================================================================

DROP VIEW IF EXISTS vw_equipos_dashboard CASCADE;

DROP FUNCTION IF EXISTS fn_top_equipos_solicitados(integer) CASCADE;
DROP FUNCTION IF EXISTS fn_equipo_disponible(bigint, timestamptz, timestamptz) CASCADE;
DROP FUNCTION IF EXISTS fn_generar_codigo_reserva() CASCADE;
DROP FUNCTION IF EXISTS fn_set_fecha_actualizacion() CASCADE;
DROP FUNCTION IF EXISTS fn_normalizar_validar_usuario() CASCADE;
DROP FUNCTION IF EXISTS fn_asignar_rol_base_usuario() CASCADE;
DROP FUNCTION IF EXISTS fn_revocar_sesiones_por_cambio_password() CASCADE;
DROP FUNCTION IF EXISTS fn_normalizar_equipo() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_cambio_estado_equipo() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_reserva() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_insercion_reserva_equipo() CASCADE;
DROP FUNCTION IF EXISTS fn_reserva_equipo_inmutable() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_reserva_con_equipo() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_configuracion() CASCADE;
DROP FUNCTION IF EXISTS fn_crear_sesion(bigint, varchar, varchar, varchar) CASCADE;
DROP FUNCTION IF EXISTS fn_crear_recuperacion_password(bigint, varchar, varchar, varchar) CASCADE;
DROP FUNCTION IF EXISTS fn_rotar_refresh_token(varchar, varchar) CASCADE;
DROP FUNCTION IF EXISTS fn_revocar_sesiones_usuario(bigint, bigint) CASCADE;
DROP FUNCTION IF EXISTS fn_aplicar_recuperacion_password(varchar, varchar) CASCADE;
DROP FUNCTION IF EXISTS fn_auditoria_inmutable() CASCADE;
DROP FUNCTION IF EXISTS fn_registrar_auditoria(varchar, bigint, bigint, varchar, jsonb, jsonb, varchar, varchar, uuid) CASCADE;
DROP FUNCTION IF EXISTS fn_jsonb_contiene_clave_sensible(jsonb) CASCADE;

DROP TABLE IF EXISTS tbl_auditoria CASCADE;
DROP TABLE IF EXISTS tbl_tipo_evento_auditoria CASCADE;
DROP TABLE IF EXISTS tbl_nivel_auditoria CASCADE;

DROP TABLE IF EXISTS tbl_configuracion CASCADE;
DROP TABLE IF EXISTS tbl_categoria_configuracion CASCADE;

DROP TABLE IF EXISTS tbl_reserva_equipo CASCADE;
DROP TABLE IF EXISTS tbl_reserva CASCADE;

DROP TABLE IF EXISTS tbl_equipo CASCADE;
DROP TABLE IF EXISTS tbl_ubicacion CASCADE;
DROP TABLE IF EXISTS tbl_categoria_equipo CASCADE;

DROP TABLE IF EXISTS tbl_recuperacion_password CASCADE;
DROP TABLE IF EXISTS tbl_sesion CASCADE;
DROP TABLE IF EXISTS tbl_usuario_rol CASCADE;
DROP TABLE IF EXISTS tbl_usuario CASCADE;
DROP TABLE IF EXISTS tbl_idioma CASCADE;
DROP TABLE IF EXISTS tbl_rol CASCADE;

DROP TABLE IF EXISTS tbl_estado_reserva CASCADE;
DROP TABLE IF EXISTS tbl_estado_equipo CASCADE;
DROP TABLE IF EXISTS tbl_estado_usuario CASCADE;
DROP TABLE IF EXISTS tbl_estado_registro CASCADE;

DROP SEQUENCE IF EXISTS seq_codigo_reserva CASCADE;


-- ============================================================================
-- 1. ESTADOS
-- ============================================================================

CREATE TABLE tbl_estado_registro (
    id_estado_registro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(60) NOT NULL,
    descripcion varchar(255),

    CONSTRAINT uq_estado_registro_codigo UNIQUE (codigo),
    CONSTRAINT uq_estado_registro_nombre UNIQUE (nombre),

    CONSTRAINT ck_estado_registro_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_estado_registro_nombre
        CHECK (length(btrim(nombre)) > 0)
);


CREATE TABLE tbl_estado_usuario (
    id_estado_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(60) NOT NULL,
    descripcion varchar(255),

    CONSTRAINT uq_estado_usuario_codigo UNIQUE (codigo),
    CONSTRAINT uq_estado_usuario_nombre UNIQUE (nombre),

    CONSTRAINT ck_estado_usuario_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_estado_usuario_nombre
        CHECK (length(btrim(nombre)) > 0)
);


CREATE TABLE tbl_estado_equipo (
    id_estado_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(40) NOT NULL,
    nombre varchar(80) NOT NULL,
    descripcion varchar(255),

    CONSTRAINT uq_estado_equipo_codigo UNIQUE (codigo),
    CONSTRAINT uq_estado_equipo_nombre UNIQUE (nombre),

    CONSTRAINT ck_estado_equipo_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_estado_equipo_nombre
        CHECK (length(btrim(nombre)) > 0)
);


CREATE TABLE tbl_estado_reserva (
    id_estado_reserva integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(40) NOT NULL,
    nombre varchar(80) NOT NULL,
    descripcion varchar(255),

    CONSTRAINT uq_estado_reserva_codigo UNIQUE (codigo),
    CONSTRAINT uq_estado_reserva_nombre UNIQUE (nombre),

    CONSTRAINT ck_estado_reserva_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_estado_reserva_nombre
        CHECK (length(btrim(nombre)) > 0)
);


-- ============================================================================
-- 2. USUARIOS, AUTENTICACIÓN Y AUTORIZACIÓN
-- ============================================================================

CREATE TABLE tbl_rol (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(60) NOT NULL,
    descripcion varchar(255),
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_rol_codigo UNIQUE (codigo),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre),

    CONSTRAINT fk_rol_estado_registro
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_rol_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_rol_nombre
        CHECK (length(btrim(nombre)) > 0)
);

CREATE INDEX idx_rol_estado_registro
    ON tbl_rol (id_estado_registro);


CREATE TABLE tbl_idioma (
    id_idioma integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(10) NOT NULL,
    nombre varchar(60) NOT NULL,
    nombre_nativo varchar(60) NOT NULL,
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_idioma_codigo UNIQUE (codigo),

    CONSTRAINT fk_idioma_estado_registro
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_idioma_codigo
        CHECK (
            codigo = btrim(codigo)
            AND codigo ~ '^[a-z]{2,3}(-[A-Z]{2})?$'
        ),

    CONSTRAINT ck_idioma_nombre
        CHECK (length(btrim(nombre)) > 0),

    CONSTRAINT ck_idioma_nombre_nativo
        CHECK (length(btrim(nombre_nativo)) > 0)
);

CREATE INDEX idx_idioma_estado_registro
    ON tbl_idioma (id_estado_registro);


CREATE TABLE tbl_usuario (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo varchar(150) NOT NULL,
    password_hash varchar(255),
    google_sub varchar(255),
    nombres varchar(100) NOT NULL,
    apellidos varchar(100) NOT NULL,
    id_estado_usuario integer NOT NULL,
    id_idioma integer,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(),
    fecha_cambio_password timestamptz,
    ultimo_acceso timestamptz,

    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT uq_usuario_google_sub UNIQUE (google_sub),

    CONSTRAINT fk_usuario_estado_usuario
        FOREIGN KEY (id_estado_usuario)
        REFERENCES tbl_estado_usuario (id_estado_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_usuario_idioma
        FOREIGN KEY (id_idioma)
        REFERENCES tbl_idioma (id_idioma)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_usuario_correo_normalizado
        CHECK (
            correo = lower(btrim(correo))
            AND correo ~ '^[^@[:space:]]+@[^@[:space:]]+$'
        ),

    CONSTRAINT ck_usuario_password_hash
        CHECK (
            password_hash IS NULL
            OR password_hash LIKE '$argon2id$%'
        ),

    CONSTRAINT ck_usuario_google_sub
        CHECK (
            google_sub IS NULL
            OR length(btrim(google_sub)) > 0
        ),

    CONSTRAINT ck_usuario_mecanismo_autenticacion
        CHECK (
            password_hash IS NOT NULL
            OR google_sub IS NOT NULL
        ),

    CONSTRAINT ck_usuario_nombres
        CHECK (length(btrim(nombres)) > 0),

    CONSTRAINT ck_usuario_apellidos
        CHECK (length(btrim(apellidos)) > 0)
);

CREATE INDEX idx_usuario_estado
    ON tbl_usuario (id_estado_usuario);

CREATE INDEX idx_usuario_idioma
    ON tbl_usuario (id_idioma);

CREATE INDEX idx_usuario_ultimo_acceso
    ON tbl_usuario (ultimo_acceso DESC);


CREATE TABLE tbl_usuario_rol (
    id_usuario_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL,
    id_rol integer NOT NULL,
    id_estado_registro integer NOT NULL,
    fecha_asignacion timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_usuario_rol UNIQUE (id_usuario, id_rol),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES tbl_rol (id_rol)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_usuario_rol_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE INDEX idx_usuario_rol_usuario
    ON tbl_usuario_rol (id_usuario);

CREATE INDEX idx_usuario_rol_rol
    ON tbl_usuario_rol (id_rol);

CREATE INDEX idx_usuario_rol_estado
    ON tbl_usuario_rol (id_estado_registro);


CREATE TABLE tbl_sesion (
    id_sesion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL,
    refresh_token_hash varchar(128) NOT NULL,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_expiracion timestamptz NOT NULL,
    fecha_ultimo_uso timestamptz,
    fecha_revocacion timestamptz,
    ip_origen varchar(45),
    user_agent varchar(500),

    CONSTRAINT uq_sesion_refresh_token_hash UNIQUE (refresh_token_hash),

    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_sesion_refresh_hash
        CHECK (
            refresh_token_hash = lower(refresh_token_hash)
            AND refresh_token_hash ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT ck_sesion_expiracion
        CHECK (fecha_expiracion > fecha_creacion),

    CONSTRAINT ck_sesion_ultimo_uso
        CHECK (
            fecha_ultimo_uso IS NULL
            OR fecha_ultimo_uso >= fecha_creacion
        ),

    CONSTRAINT ck_sesion_revocacion
        CHECK (
            fecha_revocacion IS NULL
            OR fecha_revocacion >= fecha_creacion
        )
);

CREATE INDEX idx_sesion_usuario
    ON tbl_sesion (id_usuario);

CREATE INDEX idx_sesion_expiracion
    ON tbl_sesion (fecha_expiracion);

CREATE INDEX idx_sesion_usuario_expiracion
    ON tbl_sesion (id_usuario, fecha_expiracion DESC);

CREATE INDEX idx_sesion_activas_usuario
    ON tbl_sesion (id_usuario, fecha_expiracion DESC)
    WHERE fecha_revocacion IS NULL;


CREATE TABLE tbl_recuperacion_password (
    id_recuperacion_password bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL,
    token_hash varchar(128) NOT NULL,
    fecha_solicitud timestamptz NOT NULL DEFAULT now(),
    fecha_expiracion timestamptz NOT NULL,
    fecha_uso timestamptz,
    fecha_revocacion timestamptz,
    ip_solicitud varchar(45),
    user_agent varchar(500),

    CONSTRAINT uq_recuperacion_password_token_hash UNIQUE (token_hash),

    CONSTRAINT fk_recuperacion_password_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_recuperacion_password_hash
        CHECK (
            token_hash = lower(token_hash)
            AND token_hash ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT ck_recuperacion_password_expiracion
        CHECK (fecha_expiracion > fecha_solicitud),

    CONSTRAINT ck_recuperacion_password_uso
        CHECK (
            fecha_uso IS NULL
            OR fecha_uso >= fecha_solicitud
        ),

    CONSTRAINT ck_recuperacion_password_revocacion
        CHECK (
            fecha_revocacion IS NULL
            OR fecha_revocacion >= fecha_solicitud
        ),

    CONSTRAINT ck_recuperacion_password_no_uso_y_revocacion
        CHECK (
            NOT (
                fecha_uso IS NOT NULL
                AND fecha_revocacion IS NOT NULL
            )
        )
);

CREATE INDEX idx_recuperacion_password_usuario
    ON tbl_recuperacion_password (id_usuario);

CREATE INDEX idx_recuperacion_password_usuario_fecha
    ON tbl_recuperacion_password (id_usuario, fecha_solicitud DESC);

CREATE INDEX idx_recuperacion_password_pendiente
    ON tbl_recuperacion_password (id_usuario, fecha_expiracion)
    WHERE fecha_uso IS NULL
      AND fecha_revocacion IS NULL;


-- ============================================================================
-- 3. INVENTARIO
-- ============================================================================

CREATE TABLE tbl_categoria_equipo (
    id_categoria_equipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(40) NOT NULL,
    nombre varchar(80) NOT NULL,
    descripcion varchar(255),
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_categoria_equipo_codigo UNIQUE (codigo),
    CONSTRAINT uq_categoria_equipo_nombre UNIQUE (nombre),

    CONSTRAINT fk_categoria_equipo_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_categoria_equipo_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_categoria_equipo_nombre
        CHECK (length(btrim(nombre)) > 0)
);

CREATE INDEX idx_categoria_equipo_estado
    ON tbl_categoria_equipo (id_estado_registro);


CREATE TABLE tbl_ubicacion (
    id_ubicacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(40) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion varchar(255),
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_ubicacion_codigo UNIQUE (codigo),
    CONSTRAINT uq_ubicacion_nombre UNIQUE (nombre),

    CONSTRAINT fk_ubicacion_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_ubicacion_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_ubicacion_nombre
        CHECK (length(btrim(nombre)) > 0)
);

CREATE INDEX idx_ubicacion_estado
    ON tbl_ubicacion (id_estado_registro);


CREATE TABLE tbl_equipo (
    id_equipo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_inventario varchar(60) NOT NULL,
    nombre varchar(120) NOT NULL,
    descripcion text,
    numero_serie varchar(120),
    direccion_mac varchar(17),
    imagen_url varchar(500),
    id_categoria_equipo integer NOT NULL,
    id_estado_equipo integer NOT NULL,
    id_ubicacion integer,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_equipo_codigo_inventario UNIQUE (codigo_inventario),
    CONSTRAINT uq_equipo_numero_serie UNIQUE (numero_serie),
    CONSTRAINT uq_equipo_direccion_mac UNIQUE (direccion_mac),

    CONSTRAINT fk_equipo_categoria
        FOREIGN KEY (id_categoria_equipo)
        REFERENCES tbl_categoria_equipo (id_categoria_equipo)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_equipo_estado
        FOREIGN KEY (id_estado_equipo)
        REFERENCES tbl_estado_equipo (id_estado_equipo)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_equipo_ubicacion
        FOREIGN KEY (id_ubicacion)
        REFERENCES tbl_ubicacion (id_ubicacion)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_equipo_codigo_inventario
        CHECK (
            codigo_inventario = upper(btrim(codigo_inventario))
            AND codigo_inventario ~ '^[A-Z0-9._/-]+$'
        ),

    CONSTRAINT ck_equipo_nombre
        CHECK (length(btrim(nombre)) > 0),

    CONSTRAINT ck_equipo_serie_o_mac
        CHECK (
            numero_serie IS NOT NULL
            OR direccion_mac IS NOT NULL
        ),

    CONSTRAINT ck_equipo_numero_serie
        CHECK (
            numero_serie IS NULL
            OR length(btrim(numero_serie)) > 0
        ),

    CONSTRAINT ck_equipo_direccion_mac
        CHECK (
            direccion_mac IS NULL
            OR (
                direccion_mac = lower(direccion_mac)
                AND direccion_mac ~ '^([0-9a-f]{2}:){5}[0-9a-f]{2}$'
            )
        )
);

CREATE INDEX idx_equipo_nombre
    ON tbl_equipo (nombre);

CREATE INDEX idx_equipo_categoria
    ON tbl_equipo (id_categoria_equipo);

CREATE INDEX idx_equipo_estado
    ON tbl_equipo (id_estado_equipo);

CREATE INDEX idx_equipo_ubicacion
    ON tbl_equipo (id_ubicacion);

CREATE INDEX idx_equipo_categoria_estado
    ON tbl_equipo (id_categoria_equipo, id_estado_equipo);


-- ============================================================================
-- 4. RESERVAS
-- ============================================================================

CREATE TABLE tbl_reserva (
    id_reserva bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_reserva varchar(40) NOT NULL,
    id_usuario bigint NOT NULL,
    id_estado_reserva integer NOT NULL,
    fecha_inicio timestamptz NOT NULL,
    fecha_fin timestamptz NOT NULL,
    observaciones text,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(),
    fecha_cancelacion timestamptz,
    id_usuario_cancelacion bigint,
    motivo_cancelacion text,

    CONSTRAINT uq_reserva_codigo UNIQUE (codigo_reserva),

    CONSTRAINT fk_reserva_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_reserva_estado
        FOREIGN KEY (id_estado_reserva)
        REFERENCES tbl_estado_reserva (id_estado_reserva)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_reserva_usuario_cancelacion
        FOREIGN KEY (id_usuario_cancelacion)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_reserva_codigo
        CHECK (
            codigo_reserva = upper(btrim(codigo_reserva))
            AND length(btrim(codigo_reserva)) > 0
        ),

    CONSTRAINT ck_reserva_fechas
        CHECK (fecha_fin > fecha_inicio),

    CONSTRAINT ck_reserva_cancelacion
        CHECK (
            (
                fecha_cancelacion IS NULL
                AND id_usuario_cancelacion IS NULL
            )
            OR
            (
                fecha_cancelacion IS NOT NULL
                AND id_usuario_cancelacion IS NOT NULL
            )
        ),

    CONSTRAINT ck_reserva_motivo_cancelacion
        CHECK (
            motivo_cancelacion IS NULL
            OR length(btrim(motivo_cancelacion)) > 0
        )
);

CREATE INDEX idx_reserva_usuario
    ON tbl_reserva (id_usuario);

CREATE INDEX idx_reserva_estado
    ON tbl_reserva (id_estado_reserva);

CREATE INDEX idx_reserva_fecha_inicio
    ON tbl_reserva (fecha_inicio);

CREATE INDEX idx_reserva_fecha_fin
    ON tbl_reserva (fecha_fin);

CREATE INDEX idx_reserva_usuario_fecha
    ON tbl_reserva (id_usuario, fecha_inicio DESC);

CREATE INDEX idx_reserva_estado_fecha
    ON tbl_reserva (id_estado_reserva, fecha_inicio, fecha_fin);


CREATE TABLE tbl_reserva_equipo (
    id_reserva_equipo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva bigint NOT NULL,
    id_equipo bigint NOT NULL,

    CONSTRAINT uq_reserva_equipo UNIQUE (id_reserva, id_equipo),

    CONSTRAINT fk_reserva_equipo_reserva
        FOREIGN KEY (id_reserva)
        REFERENCES tbl_reserva (id_reserva)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_reserva_equipo_equipo
        FOREIGN KEY (id_equipo)
        REFERENCES tbl_equipo (id_equipo)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE INDEX idx_reserva_equipo_reserva
    ON tbl_reserva_equipo (id_reserva);

CREATE INDEX idx_reserva_equipo_equipo
    ON tbl_reserva_equipo (id_equipo);

CREATE INDEX idx_reserva_equipo_equipo_reserva
    ON tbl_reserva_equipo (id_equipo, id_reserva);


-- ============================================================================
-- 5. CONFIGURACIÓN GLOBAL
-- ============================================================================

CREATE TABLE tbl_categoria_configuracion (
    id_categoria_configuracion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(40) NOT NULL,
    nombre varchar(80) NOT NULL,
    descripcion varchar(255),
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_categoria_configuracion_codigo UNIQUE (codigo),
    CONSTRAINT uq_categoria_configuracion_nombre UNIQUE (nombre),

    CONSTRAINT fk_categoria_configuracion_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_categoria_configuracion_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_categoria_configuracion_nombre
        CHECK (length(btrim(nombre)) > 0)
);

CREATE INDEX idx_categoria_configuracion_estado
    ON tbl_categoria_configuracion (id_estado_registro);


CREATE TABLE tbl_configuracion (
    id_configuracion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave varchar(100) NOT NULL,
    valor jsonb NOT NULL,
    descripcion varchar(500),
    id_categoria_configuracion integer NOT NULL,
    id_estado_registro integer NOT NULL,
    fecha_creacion timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_configuracion_clave UNIQUE (clave),

    CONSTRAINT fk_configuracion_categoria
        FOREIGN KEY (id_categoria_configuracion)
        REFERENCES tbl_categoria_configuracion (id_categoria_configuracion)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_configuracion_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_configuracion_clave
        CHECK (
            clave = upper(btrim(clave))
            AND clave ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_configuracion_valor
        CHECK (valor <> 'null'::jsonb)
);

CREATE INDEX idx_configuracion_categoria
    ON tbl_configuracion (id_categoria_configuracion);

CREATE INDEX idx_configuracion_estado
    ON tbl_configuracion (id_estado_registro);


-- ============================================================================
-- 6. AUDITORÍA
-- ============================================================================

CREATE TABLE tbl_nivel_auditoria (
    id_nivel_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(60) NOT NULL,
    descripcion varchar(255),

    CONSTRAINT uq_nivel_auditoria_codigo UNIQUE (codigo),
    CONSTRAINT uq_nivel_auditoria_nombre UNIQUE (nombre),

    CONSTRAINT ck_nivel_auditoria_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_nivel_auditoria_nombre
        CHECK (length(btrim(nombre)) > 0)
);


CREATE TABLE tbl_tipo_evento_auditoria (
    id_tipo_evento_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(60) NOT NULL,
    nombre varchar(100) NOT NULL,
    descripcion varchar(500),
    id_nivel_auditoria integer NOT NULL,
    id_estado_registro integer NOT NULL,

    CONSTRAINT uq_tipo_evento_auditoria_codigo UNIQUE (codigo),

    CONSTRAINT fk_tipo_evento_nivel
        FOREIGN KEY (id_nivel_auditoria)
        REFERENCES tbl_nivel_auditoria (id_nivel_auditoria)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_tipo_evento_estado
        FOREIGN KEY (id_estado_registro)
        REFERENCES tbl_estado_registro (id_estado_registro)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_tipo_evento_auditoria_codigo
        CHECK (
            codigo = upper(btrim(codigo))
            AND codigo ~ '^[A-Z0-9_]+$'
        ),

    CONSTRAINT ck_tipo_evento_auditoria_nombre
        CHECK (length(btrim(nombre)) > 0)
);

CREATE INDEX idx_tipo_evento_nivel
    ON tbl_tipo_evento_auditoria (id_nivel_auditoria);

CREATE INDEX idx_tipo_evento_estado
    ON tbl_tipo_evento_auditoria (id_estado_registro);


CREATE TABLE tbl_auditoria (
    id_auditoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_actor bigint,
    id_tipo_evento_auditoria integer NOT NULL,
    id_registro_afectado bigint,
    descripcion varchar(1000),
    datos_anteriores jsonb,
    datos_nuevos jsonb,
    ip_origen varchar(45),
    user_agent varchar(500),
    correlation_id uuid,
    fecha_evento timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_auditoria_usuario_actor
        FOREIGN KEY (id_usuario_actor)
        REFERENCES tbl_usuario (id_usuario)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_auditoria_tipo_evento
        FOREIGN KEY (id_tipo_evento_auditoria)
        REFERENCES tbl_tipo_evento_auditoria (id_tipo_evento_auditoria)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_auditoria_descripcion
        CHECK (
            descripcion IS NULL
            OR length(btrim(descripcion)) > 0
        )
);

CREATE INDEX idx_auditoria_usuario_actor
    ON tbl_auditoria (id_usuario_actor);

CREATE INDEX idx_auditoria_tipo_evento
    ON tbl_auditoria (id_tipo_evento_auditoria);

CREATE INDEX idx_auditoria_fecha
    ON tbl_auditoria (fecha_evento DESC);

CREATE INDEX idx_auditoria_correlation
    ON tbl_auditoria (correlation_id);

CREATE INDEX idx_auditoria_usuario_fecha
    ON tbl_auditoria (id_usuario_actor, fecha_evento DESC);

CREATE INDEX idx_auditoria_tipo_fecha
    ON tbl_auditoria (id_tipo_evento_auditoria, fecha_evento DESC);


-- ============================================================================
-- 7. ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE tbl_estado_registro ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_estado_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_estado_equipo ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_estado_reserva ENABLE ROW LEVEL SECURITY;

ALTER TABLE tbl_rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_idioma ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_usuario_rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_sesion ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_recuperacion_password ENABLE ROW LEVEL SECURITY;

ALTER TABLE tbl_categoria_equipo ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_ubicacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_equipo ENABLE ROW LEVEL SECURITY;

ALTER TABLE tbl_reserva ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_reserva_equipo ENABLE ROW LEVEL SECURITY;

ALTER TABLE tbl_categoria_configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_configuracion ENABLE ROW LEVEL SECURITY;

ALTER TABLE tbl_nivel_auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_tipo_evento_auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbl_auditoria ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- 8. COMENTARIOS
-- ============================================================================

COMMENT ON TABLE tbl_usuario IS
'Usuarios internos. Google SSO y/o contraseña local protegida con Argon2id.';

COMMENT ON TABLE tbl_sesion IS
'Sesiones persistentes. Solo se almacena el hash del refresh token.';

COMMENT ON TABLE tbl_recuperacion_password IS
'Recuperación de contraseña mediante token de un solo uso almacenado como hash.';

COMMENT ON TABLE tbl_equipo IS
'Inventario físico de equipos del LIS. DISPONIBLE/RESERVADO se calcula en backend.';

COMMENT ON TABLE tbl_reserva IS
'Cabecera de reserva con usuario, estado y franja temporal.';

COMMENT ON TABLE tbl_reserva_equipo IS
'Relación entre reservas y equipos. El backend valida solapamientos en una transacción.';

COMMENT ON TABLE tbl_configuracion IS
'Configuraciones globales no secretas. Los secretos permanecen en variables de entorno.';

COMMENT ON TABLE tbl_auditoria IS
'Bitácora de trazabilidad. El backend debe impedir registrar contraseñas, tokens o secretos.';


COMMIT;

-- ============================================================================
-- FIN
-- ============================================================================
