services:
  postgres:
    image: postgres:16
    container_name: lis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lis_user
      POSTGRES_PASSWORD: lis_password
      POSTGRES_DB: lis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: