### Variables para test
@host = http://localhost:8080
@equipmentUrl = {{host}}/api/v1/equipment
@reservationUrl = {{host}}/api/v1/reservation
@oauth2AuthUrl = {{host}}/oauth2/authorization/google

# Este proyecto usa OAuth2 Login con Google. Para obtener el token JWT se debe:
# 1) abrir el endpoint 'http://localhost:8080/login' en el navegador (no en visual dado que es más complejo visualizar el token) e inicie sesión de Google.
# 2) ingresar con un correo institucional @udea.edu.co.
# 3) copiar el valor de "token" de la respuesta JSON.
# 4) reemplazar el valor de @token en la siguiente variable. 

@token = Bearer MODIFICAR-AQUI-CON-TOKEN-OBTENIDO

### 1. Consultar equipos (GET público)
GET {{equipmentUrl}}?page=0&size=10
Accept: application/json

### 2. Crear equipo (POST) - requiere ADMIN
POST {{equipmentUrl}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Arduino Uno R3",
  "macSerialNumber": "SN-{{$randomInt 1000 9999}}",
  "category": "MICROCONTROLADORES",
  "status": "DISPONIBLE"
}

### Crear otro equipo (categoría VR) - requiere ADMIN
POST {{equipmentUrl}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Meta Quest 33",
  "macSerialNumber": "LR-{{$randomInt 1000 9999}}",
  "category": "VR",
  "status": "DISPONIBLE"
}

### Crear equipo sin token 
POST {{equipmentUrl}}
Content-Type: application/json

{
  "name": "Equipo no autorizado",
  "macSerialNumber": "00:1A:2B:3C:4D:02",
  "category": "REDES",
  "status": "DISPONIBLE"
}

### 3. Actualizar equipo (PUT) - reemplaza {id} en las pruebas
PUT {{equipmentUrl}}/5
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Arduino Uno R5 - Actualizado",
  "category": "MICROCONTROLADORES",
  "status": "EN_MANTENIMIENTO"
}

### Actualizar equipo que no existe
PUT {{equipmentUrl}}/9999
Authorization: {{token}}
Content-Type: application/json

{
  "name": "No existe",
  "category": "REDES",
  "status": "DISPONIBLE"
}

### 4. Consultar equipo por id (GET)
GET {{equipmentUrl}}/2
Accept: application/json

### Consultar equipo que no existe 
GET {{equipmentUrl}}/9999

### 5. Listado paginado con filtros (GET)

### Listado completo (sin filtros)
GET {{equipmentUrl}}?page=0&size=10

### Filtrado por categoría
GET {{equipmentUrl}}?category=VR&page=0&size=10

### Filtrado por estado
GET {{equipmentUrl}}?status=DISPONIBLE&page=0&size=10

### Filtrado combinado (categoría + estado)
GET {{equipmentUrl}}?category=MICROCONTROLADORES&status=DISPONIBLE&page=0&size=10

### Con ordenamiento
GET {{equipmentUrl}}?page=0&size=5&sort=name,asc
