package com.lis.reservas.categoria.service;

import com.lis.reservas.categoria.dto.CategoriaRequest;
import com.lis.reservas.categoria.dto.CategoriaResponse;
import com.lis.reservas.categoria.entity.Categoria;
import com.lis.reservas.categoria.mapper.CategoriaMapper;
import com.lis.reservas.categoria.repository.CategoriaRepository;
import com.lis.reservas.common.exception.RecursoNoEncontradoException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Application service for the {@link Categoria} catalog.
 *
 * <p>The catalog is a small, read-mostly reference set: the only write
 * operation is {@link #create} used by the lab admin to register a new
 * equipment type. Reads power the public {@code GET /api/v1/categorias}
 * endpoint and the categoria dropdown when creating equipos.
 */
@Service
@RequiredArgsConstructor
public class CategoriaService {

    private final CategoriaRepository categoriaRepository;
    private final CategoriaMapper categoriaMapper;

    /**
     * @return every categoria in id order.
     */
    public List<CategoriaResponse> findAll() {
        return categoriaMapper.toResponseList(categoriaRepository.findAll());
    }

    /**
     * @param id the {@code id_categoria} primary key.
     * @return the categoria projection.
     * @throws RecursoNoEncontradoException if no categoria has that id.
     */
    public CategoriaResponse findById(Integer id) {
        return categoriaRepository.findById(id)
                .map(categoriaMapper::toResponse)
                .orElseThrow(() -> new RecursoNoEncontradoException(
                        "Categoria no encontrada: " + id));
    }

    /**
     * Persist a new categoria. The {@code id_categoria} is generated by the
     * database (IDENTITY), so the request only carries nombre + descripcion.
     */
    @Transactional
    public CategoriaResponse create(CategoriaRequest request) {
        Categoria categoria = categoriaMapper.toEntity(request);
        return categoriaMapper.toResponse(categoriaRepository.save(categoria));
    }
}
