/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as IngresoRouteImport } from './routes/ingreso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdministracionEquiposRouteImport } from './routes/administracion.equipos'
import { Route as EquiposIndexRouteImport } from './routes/equipos.index'
import { Route as EquiposEquipmentIdRouteImport } from './routes/equipos.$equipmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionEquiposRoute = AdministracionEquiposRouteImport.update({
  id: '/administracion/equipos',
  path: '/administracion/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposEquipmentIdRoute = EquiposEquipmentIdRouteImport.update({
  id: '/equipos/$equipmentId',
  path: '/equipos/$equipmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/ingreso': typeof IngresoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracion/equipos': typeof AdministracionEquiposRoute
  '/equipos/$equipmentId': typeof EquiposEquipmentIdRoute
  '/equipos/': typeof EquiposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/ingreso': typeof IngresoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracion/equipos': typeof AdministracionEquiposRoute
  '/equipos/$equipmentId': typeof EquiposEquipmentIdRoute
  '/equipos': typeof EquiposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/ingreso': typeof IngresoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar': typeof RecuperarRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracion/equipos': typeof AdministracionEquiposRoute
  '/equipos/$equipmentId': typeof EquiposEquipmentIdRoute
  '/equipos/': typeof EquiposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estadisticas'
    | '/ingreso'
    | '/perfil'
    | '/recuperar'
    | '/reservas'
    | '/reset-password'
    | '/administracion/equipos'
    | '/equipos/$equipmentId'
    | '/equipos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estadisticas'
    | '/ingreso'
    | '/perfil'
    | '/recuperar'
    | '/reservas'
    | '/reset-password'
    | '/administracion/equipos'
    | '/equipos/$equipmentId'
    | '/equipos'
  id:
    | '__root__'
    | '/'
    | '/estadisticas'
    | '/ingreso'
    | '/perfil'
    | '/recuperar'
    | '/reservas'
    | '/reset-password'
    | '/administracion/equipos'
    | '/equipos/$equipmentId'
    | '/equipos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstadisticasRoute: typeof EstadisticasRoute
  IngresoRoute: typeof IngresoRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarRoute: typeof RecuperarRoute
  ReservasRoute: typeof ReservasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdministracionEquiposRoute: typeof AdministracionEquiposRoute
  EquiposEquipmentIdRoute: typeof EquiposEquipmentIdRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/equipos': {
      id: '/administracion/equipos'
      path: '/administracion/equipos'
      fullPath: '/administracion/equipos'
      preLoaderRoute: typeof AdministracionEquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$equipmentId': {
      id: '/equipos/$equipmentId'
      path: '/equipos/$equipmentId'
      fullPath: '/equipos/$equipmentId'
      preLoaderRoute: typeof EquiposEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstadisticasRoute: EstadisticasRoute,
  IngresoRoute: IngresoRoute,
  PerfilRoute: PerfilRoute,
  RecuperarRoute: RecuperarRoute,
  ReservasRoute: ReservasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdministracionEquiposRoute: AdministracionEquiposRoute,
  EquiposEquipmentIdRoute: EquiposEquipmentIdRoute,
  EquiposIndexRoute: EquiposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
