name: Frontend CI
 
on:
  push:
    branches:
      - 1094244076-reto3
  pull_request:
    branches:
      - 1094244076-reto3
 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lis-equipment-dashboard
 
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4
 
      - name: Configurar Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: ./lis-equipment-dashboard/package-lock.json
 
      - name: Instalar dependencias
        run: npm ci
 
      - name: Build
        run: npm run build