springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

app:
  cookie:
    secure: ${COOKIE_SECURE:true}
    same-site: ${COOKIE_SAME_SITE:None}

