springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

openapi:
  server-url: ${OPENAPI_SERVER_URL:https://technical-test-2026-2-v96h.onrender.com}
  server-description: ${OPENAPI_SERVER_DESCRIPTION:Servidor de producción}

app:
  cookie:
    secure: ${COOKIE_SECURE:true}
    same-site: ${COOKIE_SAME_SITE:None}